### PR TITLE
Allow copying texts with newlines

### PR DESCRIPTION
**Pull request by premshree**
`input` elements don't allow copying newlines. A `textarea` can solve this. LMK what you think!

### CODE REVIEW

**Review by tmcw — APPROVED** [review]
Thanks!

**Comment by premshree** [comment]
Thanks @tmcw. I don't have write access, so want to merge?

**Comment by tmcw** [comment]
I also don't have write access, apparently. @ianshward can you merge?

**Comment by premshree** [comment]
@ianshward paging again, to follow up. :)

**Comment by ianshward** [comment]
@tmcw you should have access now

**Comment by premshree** [comment]
Thank you all!

**Pull request merged**
